-- AlterTable
ALTER TABLE `User` ADD COLUMN `whatsapp` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `User` ADD COLUMN `district` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `User` ADD COLUMN `gender` VARCHAR(191) NOT NULL DEFAULT '';
ALTER TABLE `User` ADD COLUMN `address` TEXT NULL;
ALTER TABLE `User` ADD COLUMN `notes` TEXT NULL;
UPDATE `User` SET `address` = '' WHERE `address` IS NULL;
UPDATE `User` SET `notes` = '' WHERE `notes` IS NULL;
ALTER TABLE `User` MODIFY `address` TEXT NOT NULL;
ALTER TABLE `User` MODIFY `notes` TEXT NOT NULL;

-- AlterTable
ALTER TABLE `Setting` ADD COLUMN `whatsappNumber` VARCHAR(191) NOT NULL DEFAULT '';
